version: '3'
services:
  app:
    build: .
    ports:
      - '5001:5000'
    depends_on:
      - mongo
      - redis
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
    command: npm start
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
